### ISSUE TITLE
decision tree

### ISSUE THREAD

**Issue by antonioaltamura** [mwasiluk/angular-surveys#11]
Hi, a 'decision tree' should allows to go to a page defined by the answer (if you anwser "yes" go to question 2, if "no" go to question 3). Is this possible?

Anyway, is angular-surveys 'production-ready'? I mean, it can be used in production or there are big known bug currently?

**Comment by mwasiluk** [comment]
Hi, a 'decision tree' should work well. Take a look at  #7.

There is no big bug I know of and angular-surveys is used in at least one fairly big project, but it's still in beta phase.
