### ISSUE TITLE
Disable/Remove submit button

### ISSUE THREAD

**Issue by shahilg** [mwasiluk/angular-surveys#19]
I want to show the preview of the created survey form by the Admin. So that other admin can see the form preview. I have used form-viewer for the preview is there some or the other way to disable or remove the submit button. 

Looking forward for the answer. Thanks

**Comment by mwasiluk** [comment]
There is now a disableSubmit option in form-viewer.

**Comment by shahilg** [comment]
Thanks @mwasiluk
