### ISSUE TITLE
RoadMap

### ISSUE THREAD

**Issue by Jorgevillada** [mwasiluk/angular-surveys#3]
Hello, the repository has roadmap? we would like to continue to contribute and know how we can collaborate and perform a work plan in order to avoid write the same features.

Thanks.

**Comment by mwasiluk** [comment]
Hi, project doesn't have a definite roadmap yet, but I have some things on todo list, eg:

- user defined (plugin like) custom page elements, with custom templates and lifecycle callbacks; all elements should work this way eventually,
- some directives for viewing/analysing responses, maybe simple charts,
- google docs integration 
- reduction of external dependencies
- tests

We can create roadmap wiki page and define roadmap there. As to collaboration, please submit new issue (with label 'enhancment') when you are about to implement something new. I'll do the same. 

Regards
