### ISSUE TITLE
translate not working

### ISSUE THREAD

**Issue by suraj740** [mwasiluk/angular-surveys#47]
screenshot added
![screen shot 2017-07-21 at 9 27 06 pm](https://user-images.githubusercontent.com/24958883/28471663-80b029fc-6e5b-11e7-8b1f-17d7586af284.png)
please help  @mwasiluk 
Thanks in advance

**Comment by mwasiluk** [comment]
Have you initialized translateProvider like in demo?
https://github.com/mwasiluk/angular-surveys/blob/master/demo-material/demo.js#L3

Regards

**Comment by suraj740** [comment]
Great, Its working now.
Thanks @mwasiluk
