### ISSUE TITLE
Material Design

### ISSUE THREAD

**Issue by erikriver** [mwasiluk/angular-surveys#8]
Hello, I want to contribute in your project, I need something similar with material design, I saw you have a branch whit some changes, How can I help you? Do you have a roadmap? in fact, I saw that there is a fork that has a lot of progress on that too:

https://github.com/theRichu/angular-surveys

Regards.

**Comment by mwasiluk** [comment]
Hi, I've merged branch with material design templates to master. 

Material templates are in directory '/src/builder/templates/material/',  and demo using these templates is in '/demo-material'. 

Files from 'dist/form-builder.min.js and 'dist/form-viewer.min.js don't contain any templates; you need to add them from file 'form-builder-material-tpls.min.js'

Online demo is here: http://mwasiluk.github.io/angular-surveys/material

Regarding the roadmap and help: https://github.com/mwasiluk/angular-surveys/issues/3

Regards.
